'use client'

import { useEffect, useRef, useState } from 'react'

import { useRouter, useSearchParams } from 'next/navigation'

import { signIn, signOut, useSession } from 'next-auth/react'
import { Box, Typography, Button } from '@mui/material'
import GlobalStyles from '@mui/material/GlobalStyles'

import Loading from '@/components/Loading'

type PageState = 'loading' | 'login' | 'processing' | 'logged-out'

/**
 * SSO Login Page - Handles redirect-based SSO flow
 *
 * Flow:
 * 1. Check if logout=true → show logout success screen with sign-in button
 * 2. If authenticated → redirect to callbackUrl
 * 3. If sso_token present (returning from SSO) → auto-complete OAuth flow
 * 4. Otherwise → show login UI with "Login with Alfred Account" button
 */

const loginGlobalStyles = (
  <GlobalStyles styles={{
    '@keyframes float': {
      '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
      '50%': { transform: 'translateY(-20px) rotate(5deg)' }
    },
    '@keyframes floatDelayed': {
      '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
      '50%': { transform: 'translateY(-20px) rotate(5deg)' }
    },
    '@keyframes fadeIn': {
      '0%': { opacity: 0, transform: 'translateY(10px)' },
      '100%': { opacity: 1, transform: 'translateY(0)' }
    },
    '@keyframes pulseGlow': {
      '0%, 100%': { boxShadow: '0 0 0 0 rgba(115, 103, 240, 0)', transform: 'scale(1)' },
      '50%': { boxShadow: '0 0 20px 2px rgba(115, 103, 240, 0.4)', transform: 'scale(1.01)' }
    },
    '@keyframes shimmer': {
      '0%': { backgroundPosition: '-200% 0' },
      '100%': { backgroundPosition: '200% 0' }
    },

    /* ── Background floating icons ── */
    '.login-bg-icon': {
      position: 'absolute',
      pointerEvents: 'none',
      display: 'none',
    },
    '@media (min-width: 1200px)': {
      '.login-bg-icon': { display: 'block' },
    },
    '[data-mui-color-scheme="dark"] .login-bg-icon': { opacity: 0.1, color: 'white' },
    '[data-mui-color-scheme="light"] .login-bg-icon, :not([data-mui-color-scheme="dark"]) .login-bg-icon': { opacity: 0.05 },
    '.login-bg-icon--shield': { top: 80, right: 80, animation: 'float 6s ease-in-out infinite' },
    '.login-bg-icon--settings': { bottom: 80, left: 80, animation: 'floatDelayed 8s ease-in-out infinite 1s' },
    '.login-bg-icon--check': { top: '50%', left: 40, animation: 'float 6s ease-in-out infinite' },
    '[data-mui-color-scheme="dark"] .login-bg-icon--check': { opacity: 0.05 },
    '[data-mui-color-scheme="light"] .login-bg-icon--check, :not([data-mui-color-scheme="dark"]) .login-bg-icon--check': { opacity: 0.03 },

    /* ── Footer ── */
    '.login-footer': {
      marginTop: 32, fontSize: '0.875rem', display: 'flex', flexDirection: 'column',
      alignItems: 'center', gap: 12, zIndex: 10, opacity: 0,
      animation: 'fadeIn 0.8s ease-out 0.8s forwards',
    },
    '[data-mui-color-scheme="dark"] .login-footer': { color: '#676d7d' },

    /* ── Fade-in animation classes (stable, never regenerated by Emotion) ── */
    '.login-fade-in': { opacity: 0, animation: 'fadeIn 0.8s ease-out forwards' },
    '.login-fade-in-d2': { opacity: 0, animation: 'fadeIn 0.8s ease-out 0.2s forwards' },
    '.login-fade-in-d3': { opacity: 0, animation: 'fadeIn 0.8s ease-out 0.3s forwards' },
    '.login-fade-in-d4': { opacity: 0, animation: 'fadeIn 0.8s ease-out 0.4s forwards' },
    '.login-fade-in-d5': { opacity: 0, animation: 'fadeIn 0.8s ease-out 0.5s forwards' },
    '.login-fade-in-d6': { opacity: 0, animation: 'fadeIn 0.8s ease-out 0.6s forwards' },

    /* ── Button pulse glow ── */
    '.login-btn-pulse': {
      animation: 'pulseGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
    },
    '.login-btn-pulse:hover': {
      animation: 'pulseGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite, shimmer 1.5s infinite linear',
    },

    /* ── Dark-mode text colors ── */
    '[data-mui-color-scheme="dark"] .login-heading': { color: '#d0d2d6' },
    '[data-mui-color-scheme="dark"] .login-subtext': { color: '#b4b7bd' },
    '[data-mui-color-scheme="dark"] .login-divider': { borderColor: '#404656' },
    '[data-mui-color-scheme="dark"] .login-divider-text': { color: '#676d7d' },
  }} />
)

// ─── Shared card wrapper ──────────────────────────────────────────────────────
const CardWrapper = ({ children }: { children: React.ReactNode }) => (
  <>
    {loginGlobalStyles}
    <Box
      sx={(theme) => ({
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '100vh',
        bgcolor: theme.palette.mode === 'dark' ? '#161d31' : 'background.default',
        p: 3,
        position: 'relative',
        overflow: 'hidden',
        color: theme.palette.mode === 'dark' ? '#b4b7bd' : 'text.secondary',
        fontFamily: '"Public Sans", sans-serif',
      })}
    >
      {/* Background float elements */}
      <div className='login-bg-icon login-bg-icon--shield'>
        <i className='tabler-shield' style={{ fontSize: 160, color: 'inherit' }} />
      </div>
      <div className='login-bg-icon login-bg-icon--settings'>
        <i className='tabler-settings' style={{ fontSize: 140, color: 'inherit' }} />
      </div>
      <div className='login-bg-icon login-bg-icon--check'>
        <i className='tabler-shield-check' style={{ fontSize: 80, color: 'inherit' }} />
      </div>

      <Box
        sx={(theme) => ({
          zIndex: 10,
          display: 'flex',
          flexDirection: 'column',
          bgcolor: theme.palette.mode === 'dark' ? '#283046' : 'background.paper',
          border: '1px solid',
          borderColor: theme.palette.mode === 'dark' ? '#404656' : 'divider',
          borderRadius: 2,
          boxShadow: theme.palette.mode === 'dark' ? '0 25px 50px -12px rgba(0, 0, 0, 0.25)' : '0 10px 30px rgba(0, 0, 0, 0.08)',
          p: { xs: 4, sm: 5 },
          maxWidth: 450,
          width: '100%',
        })}
      >
        {children}
      </Box>

      {/* Footer */}
      <div className='login-footer'>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
          <Typography variant="body2" sx={{ fontFamily: 'inherit' }}>© {new Date().getFullYear()} Alfred</Typography>
        </Box>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, opacity: 0.8 }}>
          <i className='tabler-lock' style={{ fontSize: 16 }} />
          <Typography variant="caption" sx={{ textTransform: 'uppercase', letterSpacing: '0.1em', fontFamily: 'inherit' }}>End-to-end encrypted session</Typography>
        </Box>
      </div>
    </Box>
  </>
)

export default function SSOLoginPage() {
  const { data: session, status } = useSession()
  const router = useRouter()
  const searchParams = useSearchParams()
  const hasTriggeredRef = useRef(false)
  const [pageState, setPageState] = useState<PageState>('loading')
  const [isSigningIn, setIsSigningIn] = useState(false)

  const rawCallbackUrl = searchParams.get('callbackUrl') || '/dashboards'
  const appUrl = process.env.NEXT_PUBLIC_APP_URL!

  const callbackUrl = rawCallbackUrl.startsWith('http')
    ? rawCallbackUrl
    : `${appUrl}${rawCallbackUrl.startsWith('/') ? '' : '/'}${rawCallbackUrl}`

  const isLogoutRedirect = searchParams.get('logout') === 'true'
  const ssoToken = searchParams.get('sso_token')

  useEffect(() => {
    if (isLogoutRedirect) {
      setPageState('logged-out')

      return
    }

    if (status === 'loading') return

    if (status === 'authenticated') {
      // Session may still have an error (e.g. RefreshAccessTokenError) even though the
      // cookie exists — this happens when the user arrives via AuthRedirect (which does
      // NOT call signOut). If we just redirect to the dashboard here, AuthGuard will
      // immediately render AuthRedirect again → infinite loop.
      // Fix: sign out first to clear the stale session, then start a fresh OAuth flow.
      if (session?.error) {
        if (hasTriggeredRef.current) return
        hasTriggeredRef.current = true
        setPageState('processing')
        signOut({ redirect: false }).then(() => {
          signIn('alfred-identity', { callbackUrl })
        })

        return
      }

      router.replace(rawCallbackUrl)

      return
    }

    if (status === 'unauthenticated') {
      if (ssoToken && !hasTriggeredRef.current) {
        hasTriggeredRef.current = true
        setPageState('processing')
        signIn('alfred-identity', { callbackUrl })

        return
      }

      setPageState('login')
    }
  }, [status, session, callbackUrl, rawCallbackUrl, router, searchParams, isLogoutRedirect, ssoToken])

  const handleSignIn = () => {
    setIsSigningIn(true)
    signIn('alfred-identity', { callbackUrl })
  }

  // ─── Processing / initial loading ────────────────────────────────────────────
  if (pageState === 'loading') return <>{loginGlobalStyles}<Loading message='Checking authentication...' /></>
  if (pageState === 'processing') return <>{loginGlobalStyles}<Loading message='Completing sign-in...' /></>

  // ─── Logged-out screen ────────────────────────────────────────────────────────
  if (pageState === 'logged-out') {
    return (
      <CardWrapper>
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <Box
            className='login-fade-in'
            sx={{
              width: 64,
              height: 64,
              borderRadius: 3,
              bgcolor: 'rgba(40, 199, 111, 0.1)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              mb: 3,
            }}
          >
            <i className='tabler-check' style={{ fontSize: 36, color: '#28c76f' }} />
          </Box>

          <Typography className='login-fade-in login-heading' variant='h5' fontWeight={600} sx={{ color: 'text.primary', mb: 1, fontFamily: 'inherit' }}>
            See You Soon!
          </Typography>

          <Typography className='login-fade-in-d2 login-subtext' variant='body2' sx={{ color: 'text.secondary', mb: 4, textAlign: 'center', fontFamily: 'inherit' }}>
            You have been securely logged out.
          </Typography>

          <div className='login-fade-in-d4' style={{ width: '100%', paddingTop: 8 }}>
            <Button
              variant='contained'
              fullWidth
              disabled={isSigningIn}
              endIcon={!isSigningIn && <i className='tabler-arrow-right' style={{ fontSize: 20 }} />}
              startIcon={isSigningIn ? <i className='tabler-loader-2 animate-spin' style={{ fontSize: 20 }} /> : undefined}
              onClick={handleSignIn}
              sx={{
                height: 44,
                bgcolor: '#7367f0',
                color: 'white',
                fontSize: '0.875rem',
                fontWeight: 500,
                textTransform: 'none',
                borderRadius: 1.5,
                fontFamily: 'inherit',
                transition: 'all 0.3s',
                '&:hover': { bgcolor: '#675dd8' },
              }}
            >
              {isSigningIn ? 'Redirecting...' : 'Sign In Again'}
            </Button>
          </div>
        </Box>
      </CardWrapper>
    )
  }

  // ─── Login screen ─────────────────────────────────────────────────────────────
  return (
    <CardWrapper>
      <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', mb: 4 }}>
        <Box
          className='login-fade-in'
          sx={{
            width: 64, height: 64, bgcolor: 'rgba(115, 103, 240, 0.1)', borderRadius: 3,
            display: 'flex', alignItems: 'center', justifyContent: 'center', mb: 2.5,
          }}
        >
          <i className='tabler-shield-lock' style={{ fontSize: 36, color: '#7367f0' }} />
        </Box>
        <Typography className='login-fade-in login-heading' variant='h5' fontWeight={600} sx={{ color: 'text.primary', mb: 1.5, letterSpacing: '-0.02em', fontFamily: 'inherit' }}>
          Project Alfred
        </Typography>
        <div className='login-fade-in-d2' style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '4px 12px', backgroundColor: 'rgba(115, 103, 240, 0.1)', borderRadius: 4 }}>
          <i className='tabler-shield-check' style={{ fontSize: 16, color: '#7367f0' }} />
          <Typography variant='caption' fontWeight={600} sx={{ color: '#7367f0', letterSpacing: '0.05em', textTransform: 'uppercase', fontFamily: 'inherit' }}>
            Secure SSO Only
          </Typography>
        </div>
      </Box>

      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
        <div className='login-fade-in-d3' style={{ textAlign: 'center' }}>
          <Typography className='login-heading' variant='h6' fontWeight={500} sx={{ color: 'text.primary', mb: 0.5, fontFamily: 'inherit' }}>
            Welcome to Alfred! 👋
          </Typography>
          <Typography className='login-subtext' variant='body2' sx={{ color: 'text.secondary', lineHeight: 1.6, fontFamily: 'inherit' }}>
            Please sign-in to your account and start the adventure
          </Typography>
        </div>

        <div className='login-fade-in-d4' style={{ paddingTop: 8 }}>
          <Button
            className={isSigningIn ? undefined : 'login-btn-pulse'}
            variant='contained'
            fullWidth
            disabled={isSigningIn}
            startIcon={
              isSigningIn
                ? <i className='tabler-loader-2 animate-spin' style={{ fontSize: 20 }} />
                : <i className='tabler-login' style={{ fontSize: 20 }} />
            }
            onClick={handleSignIn}
            sx={{
              height: 44,
              bgcolor: '#7367f0',
              color: 'white',
              fontSize: '0.875rem',
              fontWeight: 500,
              textTransform: 'none',
              borderRadius: 1.5,
              fontFamily: 'inherit',
              position: 'relative',
              overflow: 'hidden',
              transition: 'background-color 0.3s, box-shadow 0.3s',
              '&:hover': {
                bgcolor: '#675dd8',
                background: 'linear-gradient(90deg, #7367f0 0%, #8e85f3 45%, #a69ff6 50%, #8e85f3 55%, #7367f0 100%)',
                backgroundSize: '200% 100%',
              },
              '&.Mui-disabled': {
                bgcolor: '#7367f0',
                color: 'rgba(255,255,255,0.85)',
              },
            }}
          >
            {isSigningIn ? 'Redirecting to SSO...' : 'Log in with Alfred SSO'}
          </Button>
        </div>

        <div className='login-fade-in-d5' style={{ position: 'relative', display: 'flex', alignItems: 'center', padding: '8px 0' }}>
          <div className='login-divider' style={{ flexGrow: 1, borderTop: '1px solid', borderColor: 'inherit' }} />
          <Typography className='login-divider-text' variant='caption' sx={{ mx: 2, color: 'text.disabled', fontFamily: 'inherit' }}>
            Enterprise Security
          </Typography>
          <div className='login-divider' style={{ flexGrow: 1, borderTop: '1px solid', borderColor: 'inherit' }} />
        </div>

        <div className='login-fade-in-d6' style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 24, paddingTop: 8 }}>
          <button type='button' style={{ display: 'flex', alignItems: 'center', gap: 4, color: '#7367f0', background: 'transparent', border: 'none', cursor: 'pointer', fontSize: '0.875rem', fontWeight: 500, fontFamily: 'inherit', padding: 0 }}>
            <i className='tabler-help' style={{ fontSize: 18 }} />
            <span>Help Center</span>
          </button>
          <button type='button' style={{ display: 'flex', alignItems: 'center', gap: 4, color: '#7367f0', background: 'transparent', border: 'none', cursor: 'pointer', fontSize: '0.875rem', fontWeight: 500, fontFamily: 'inherit', padding: 0 }}>
            <i className='tabler-server' style={{ fontSize: 18 }} />
            <span>System Status</span>
          </button>
        </div>
      </Box>
    </CardWrapper>
  )
}
